### PR TITLE
Properly handle middleware releasing jobs

### LINKED ISSUE #66: Show when middleware releases a job
**Describe the bug**
When a job is released via middleware, such as when using rate limiting or Without Overlapping, the job is marked as successful and a retry is created. 

This is a bit odd, as at first glance on the dashboard it looks like the job has been retried lots, not that it's been delayed due to middleware.

**To Reproduce**
1. Dispatch a rate limited job
2. See the retries be created for the job

**Expected behavior**
I expect to be able to see the job was delayed due to middleware. Nothing will have happened in the job so it should have a 'released' status and show up on the top bar in a drop-down of 'middleware delayed' jobs.

Open to other solutions to simplify the UI

### PR DESCRIPTION
**Pull request by tobytwigger**
Fixes #66

### CODE REVIEW

File: dashboard/src/components/RunShowToggleRunBar.vue [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+watch(() => props.jobRun, (newRun, oldRun) => {
+  if(props.modelValue.id === newRun.id) {
+    viewRun(newRun.id);
+  }
+});
+
+function viewRun(runId: number) {
+  let run = getRun(runId);
+  console.log(run);
```
Comment (tobytwigger) [inline dashboard/src/components/RunShowToggleRunBar.vue:35]: Remove

File: dashboard/src/components/RunShowToggleRunBar.vue [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+
+function getRun(runId: number): JobRun|null {
+  let jobRun: JobRun | null = props.jobRun;
+
+  while (jobRun !== null) {
+    if(jobRun.id.toString() === runId.toString()) {
+      return jobRun;
+    }
+    for(let releasedRun of jobRun.released_runs) {
+      console.log('checking ID ' + releasedRun.id.toString());
```
Comment (tobytwigger) [inline dashboard/src/components/RunShowToggleRunBar.vue:47]: Remove

File: dashboard/src/components/RunShowToggleRunBar.vue [hunk 3]
```diff
@@ -0,0 +1,84 @@
...
+const jobLists = computed((): JobRun[] => {
+  let jobs: JobRun[] = [];
+
+  let jobRun: JobRun | null = props.jobRun;
+  while (jobRun !== null) {
+    jobs.push(jobRun);
+    jobRun = jobRun.parent;
+  }
+
+  // Iterate through each of the jobs, from oldest first.
```
Comment (tobytwigger) [inline dashboard/src/components/RunShowToggleRunBar.vue:72]: Remove
